In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import os
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from keras.preprocessing.text import Tokenizer
print(os.listdir("../input"))
from keras.preprocessing.sequence import pad_sequences
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory
from collections import Counter
import tensorflow as tf
# Any results you write to the current directory are saved as output.

Using TensorFlow backend.
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarn

['englishfrench']


/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWa

In [2]:
with open("../input/englishfrench/small_vocab_en.txt") as f:
    eng=f.read()
    
with open("../input/englishfrench/small_vocab_fr.txt") as f:
    fr=f.read()

In [3]:
fr=fr.split("\n")
eng=eng.split("\n")

In [4]:
countengwords=Counter([w for sent in eng for w in sent.split(" ")])
countfrwords=Counter([w for sent in fr for w in sent.split(" ")])

In [5]:
engtokenizer=Tokenizer()
frtokenizer=Tokenizer()
engtokenizer.fit_on_texts(eng)
frtokenizer.fit_on_texts(fr)
tokeneng=engtokenizer.texts_to_sequences(eng)
tokenfre=frtokenizer.texts_to_sequences(fr)

In [6]:
enword_ind=engtokenizer.word_index
enword_ind['<pad>']=0

In [7]:
frword_ind=frtokenizer.word_index
frword_ind['<PAD>']=0
frword_ind['<start>']=len(frword_ind)
frword_ind['<end>']=len(frword_ind)

In [8]:
tokenfrein=[[frword_ind['<start>']]+i for i in tokenfre]
tokenfreout=[i+[frword_ind['<end>']] for i in tokenfre]

In [9]:
tokenpadfrin=pad_sequences(tokenfrein,padding='post')

In [10]:
tokenpadfrin[:5]

array([[346, 337,  34,   1,   8,  67,  37,  11,  24,   6,   3,   1, 112,
          2,  50,   0,   0,   0,   0,   0,   0,   0],
       [346,   4,  32,  31,   1,  12,  19,   2,  49,   6,   3,  95,  69,
          2,  51,   0,   0,   0,   0,   0,   0,   0],
       [346, 101,   1,  12,  67,   2,  45,   6,   3,   1,  12,  21,   2,
         41,   0,   0,   0,   0,   0,   0,   0,   0],
       [346,   4,  32,  31,   1,   8, 269,   2,  41,   6,   3, 103,  19,
          2,  48,   0,   0,   0,   0,   0,   0,   0],
       [346,  40,  13,  14,  16,   1,  10,  82,   5,  39,  13,  14,   1,
          7,  83,   0,   0,   0,   0,   0,   0,   0]], dtype=int32)

In [11]:
tokenpadfrout=pad_sequences(tokenfreout,padding='post')

In [12]:
tokenpadfrout[:5]

array([[337,  34,   1,   8,  67,  37,  11,  24,   6,   3,   1, 112,   2,
         50, 347,   0,   0,   0,   0,   0,   0,   0],
       [  4,  32,  31,   1,  12,  19,   2,  49,   6,   3,  95,  69,   2,
         51, 347,   0,   0,   0,   0,   0,   0,   0],
       [101,   1,  12,  67,   2,  45,   6,   3,   1,  12,  21,   2,  41,
        347,   0,   0,   0,   0,   0,   0,   0,   0],
       [  4,  32,  31,   1,   8, 269,   2,  41,   6,   3, 103,  19,   2,
         48, 347,   0,   0,   0,   0,   0,   0,   0],
       [ 40,  13,  14,  16,   1,  10,  82,   5,  39,  13,  14,   1,   7,
         83, 347,   0,   0,   0,   0,   0,   0,   0]], dtype=int32)

In [13]:
tokenpadeng=pad_sequences(tokeneng,padding='post')

In [14]:
batchsize=64

In [15]:
maxenglen=tokenpadeng.shape[1]
maxfrlen=tokenpadfrin.shape[1]

In [16]:
maxlen=max(maxenglen,maxfrlen)

In [17]:
maxenglen

15

In [18]:
def positional_embedding(pos, model_size):
    PE = np.zeros((1, model_size))
    for i in range(model_size):
        if i % 2 == 0:
            PE[:,i] = np.sin(pos / 10000 ** (i / model_size))
        else:
            PE[:,i] = np.cos(pos / 10000 ** ((i - 1) / model_size))
    return PE

# max_length = max(len(data_en[0]), len(data_fr_in[0]))
MODEL_SIZE = 128

pes = []
for i in range(maxenglen):
    pes.append(positional_embedding(i, MODEL_SIZE))

pes = np.concatenate(pes, axis=0)
pes = tf.constant(pes, dtype=tf.float32)

In [19]:
# h is number of heads for multihead attention at single step

In [20]:
x=tf.placeholder(dtype=tf.int32,shape=[None,maxenglen])
y=tf.placeholder(dtype=tf.int32,shape=[None,maxfrlen])
ytruth=tf.placeholder(dtype=tf.int32,shape=[None,maxfrlen])

In [21]:
maxfrlen

22

In [22]:
modelsize=128
h=2
numlayers=2

In [23]:
def multiheadattention(modelsize,h):
    querysize=modelsize//h
    keysize=modelsize//h
    valuesize=modelsize//h
    wq=[tf.keras.layers.Dense(querysize) for _ in range(h)]
    wk=[tf.keras.layers.Dense(keysize) for _ in range(h)]
    wv=[tf.keras.layers.Dense(valuesize) for _ in range(h)]
    wo=tf.keras.layers.Dense(modelsize)
    
    return wq,wk,wv,wo,keysize
    

In [24]:
def call(query,value,keysize,h,wq,wk,wv,wo):
    # query has shape (batch , querylen , modelsize)
    # value has shape (batch , valuelen , modelsize)
    heads=[]
    for i in range(h):
        score=tf.matmul(wq[i](query),wk[i](value),transpose_b=True)
        
        score/=tf.math.sqrt(tf.dtypes.cast(keysize,tf.float32))
        
        alignment=tf.nn.softmax(score,axis=2)
        
        head=tf.matmul(alignment,wv[i](value))    # head has shape  batch x decoderlen x valuesize
        
        heads.append(head)
        
    heads=tf.concat(heads,axis=2)
    heads=wo(heads)      # heards has shape batch x querylen x modelsize
    
    return heads

In [25]:
modelsize

128

In [26]:
embedvar=tf.Variable(tf.random_normal(shape=(len(enword_ind),modelsize)))

In [27]:
wq1,wk1,wv1,wo1,keysize1=multiheadattention(modelsize,h)

In [28]:
wq2,wk2,wv2,wo2,keysize2=multiheadattention(modelsize,h)

In [29]:
wq1

In [30]:
wq2

In [31]:
x.shape

TensorShape([Dimension(None), Dimension(15)])

In [32]:
pes

<tf.Tensor 'Const:0' shape=(15, 128) dtype=float32>

In [33]:
sub1=[]
for i in range(x.shape[1]):
    embed=tf.nn.embedding_lookup(embedvar,tf.expand_dims(x[:,i],axis=1))
    sub1.append(embed+pes[i,:])

subconcat1=tf.concat(sub1,axis=1)
    

In [34]:
subconcat1.shape

TensorShape([Dimension(None), Dimension(15), Dimension(128)])

In [35]:
#we are adding positional embeddings to word embeddings

In [36]:
tf.expand_dims(subconcat1[:,1,:],axis=1)

<tf.Tensor 'ExpandDims_15:0' shape=(?, 1, 128) dtype=float32>

In [37]:
e=call(tf.expand_dims(subconcat1[:,1,:],axis=1),subconcat1,keysize1,h,wq1,wk1,wv1,wo1)

In [38]:
e

<tf.Tensor 'dense_6/BiasAdd:0' shape=(?, 1, 128) dtype=float32>

In [39]:
subout=[]
for j in range(subconcat1.shape[1]):
    attention1=call( tf.expand_dims(subconcat1[:,j,:],axis=1),subconcat1,keysize1,h,wq1,wk1,wv1,wo1)
    subout.append(attention1)
subout=tf.concat(subout,axis=1)


In [40]:
subout=subout+subconcat1

In [41]:
subout

<tf.Tensor 'add_15:0' shape=(?, 15, 128) dtype=float32>

In [42]:
subout=tf.keras.layers.BatchNormalization()(subout)
ffin = tf.keras.layers.Dense(4*modelsize,activation=tf.nn.relu)(subout)
ffin1 = tf.keras.layers.Dense(modelsize)(ffin)

In [43]:
ffout=ffin1+subout
ffoutnorm=tf.keras.layers.BatchNormalization()(ffout)

In [44]:
ffoutnorm

<tf.Tensor 'batch_normalization_1/batchnorm/add_1:0' shape=(?, 15, 128) dtype=float32>

In [45]:
subin2=ffoutnorm

In [46]:
subout2=[]
for j in range(subconcat1.shape[1]):
    attention2=call( tf.expand_dims(subin2[:,j,:],axis=1),subin2,keysize2,h,wq2,wk2,wv2,wo2)
    subout2.append(attention2)
subout2=tf.concat(subout2,axis=1)
    

In [47]:
subout2=subout2+subin2
subout2=tf.keras.layers.BatchNormalization()(subout2)
ffin2 = tf.keras.layers.Dense(4*modelsize,activation=tf.nn.relu)(subout2)
ffin2 = tf.keras.layers.Dense(modelsize)(ffin2)

In [48]:
ffout2=ffin2+subout2
ffoutnorm2=tf.keras.layers.BatchNormalization()(ffout2)

In [49]:
encoderoutput=ffoutnorm2

In [50]:
encoderoutput

<tf.Tensor 'batch_normalization_3/batchnorm/add_1:0' shape=(?, 15, 128) dtype=float32>

In [51]:
dembedvar=tf.Variable(tf.random_normal(shape=(len(frword_ind),modelsize)))


In [52]:
dwq1,dwk1,dwv1,dwo1,dkeysize1=multiheadattention(modelsize,h)

In [53]:
dwq2,dwk2,dwv2,dwo2,dkeysize2=multiheadattention(modelsize,h)

In [54]:
deemb=[]
for i in range(y.shape[1]):
    dmb=tf.nn.embedding_lookup(dembedvar,tf.expand_dims(y[:,i],axis=1))
    deemb.append(dmb)

In [55]:
deemb=tf.concat(deemb,axis=1)

In [56]:
deemb

<tf.Tensor 'concat_34:0' shape=(?, 22, 128) dtype=float32>

In [57]:
botsubin=deemb


In [58]:
botsubin[:,:2,:]

<tf.Tensor 'strided_slice_84:0' shape=(?, 2, 128) dtype=float32>

In [59]:
tf.expand_dims(botsubin[:,3,:],axis=1)

<tf.Tensor 'ExpandDims_69:0' shape=(?, 1, 128) dtype=float32>

In [60]:
botsubout1=[]
for j in range(botsubin.shape[1]):
    values=botsubin[:,j,:]
    attention=call(tf.expand_dims(botsubin[:,j,:],axis=1),botsubin[:,:j,:],dkeysize1,h,dwq1,dwk1,dwv1,dwo1)
    botsubout1.append(attention)

botsubout1=tf.concat(botsubout1,axis=1)
botsubout1=botsubout1+botsubin
botsubout1=tf.keras.layers.BatchNormalization()(botsubout1)

In [61]:
midsubin=botsubout1

In [62]:
midsubin

<tf.Tensor 'batch_normalization_4/batchnorm/add_1:0' shape=(?, 22, 128) dtype=float32>

In [63]:
damwq1,damwk1,damwv1,damwo1,damkeysize1=multiheadattention(modelsize,h)
damwq2,damwk2,damwv2,damwo2,damkeysize2=multiheadattention(modelsize,h)

In [64]:
midsubout=[]
for j in range(midsubin.shape[1]):
    datt=call(tf.expand_dims(midsubin[:,j,:],axis=1),encoderoutput,damkeysize1,h,damwq1,damwk1,damwv1,damwo1)
    midsubout.append(datt)
    

In [65]:
midsubout1=tf.concat(midsubout,axis=1)
midsubout11=midsubout1+midsubin

In [66]:
midsubout11

<tf.Tensor 'add_20:0' shape=(?, 22, 128) dtype=float32>

In [67]:
midsubout12=tf.keras.layers.BatchNormalization()(midsubout11)

In [68]:
midsubout12

<tf.Tensor 'batch_normalization_5/batchnorm/add_1:0' shape=(?, 22, 128) dtype=float32>

In [69]:
# in the above step 
# we multiply query variable matrix with decoder output 
# key variable matrix with encoder output for attention 

In [70]:
dffin=midsubout12
dffout=tf.keras.layers.Dense(4*modelsize,activation=tf.nn.relu)(dffin)
dffout=tf.keras.layers.Dense(modelsize)(dffout)

In [71]:
dffin

<tf.Tensor 'batch_normalization_5/batchnorm/add_1:0' shape=(?, 22, 128) dtype=float32>

In [72]:
dffout=dffout+dffin
dffout=tf.keras.layers.BatchNormalization()(dffout)

In [73]:
logits1=tf.keras.layers.Dense(len(frword_ind))(dffout)

In [74]:
logits1.get_shape()

TensorShape([Dimension(None), Dimension(22), Dimension(348)])

In [95]:
loss=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits1,labels=tf.one_hot(ytruth,len(frword_ind))))

In [96]:
trainoptimizer=tf.train.AdamOptimizer(learning_rate=0.001)

In [97]:
trainstep=trainoptimizer.minimize(loss)

In [98]:
sess=tf.InteractiveSession()

/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py:1735: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [99]:
sess.run(tf.global_variables_initializer())

In [100]:
np.arange(64)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [90]:
l1=loss.eval({x:xinp,y:yinp,ytruth:yout})

In [91]:
l1.shape

(64, 22)

In [101]:
for i in range(100):
    ind=np.random.choice(np.arange(len(tokeneng)),size=batchsize,replace=False)
    xinp=tokenpadeng[ind]
    yinp=tokenpadfrin[ind]
    yout=tokenpadfrout[ind]
    _=sess.run(trainstep,feed_dict={x:xinp,y:yinp,ytruth:yout})
    loss1=loss.eval({x:xinp,y:yinp,ytruth:yout})
    
    if i%5==0:
        print(loss1)

6.078005
3.6313963
2.625546
2.145038
1.7299926
1.524302
1.4399065
1.15061
1.0478468
0.9696827
0.9614678
0.9152987
0.8642084
0.8155952
0.6957758
0.78014636
0.68634444
0.6570966
0.6345236
0.58594936
